### ISSUE TITLE
REVOKE

### ISSUE THREAD

**Issue by carrotcypher** [canarytail/standard#2]
An argument was made to add a REVOKE option. The merits of this need to be discussed more.

**Comment by carrotcypher** [comment]
Thought process:

1. an active canary will die eventually anyway, so if you NEWKEY to make a new one, that should allow for transition to a new canary without any unnecessary triggering 
2. what situation would someone want to cancel their canary for? closing down their business for good? isn't a canary being revoked pretty much making the statement that they no longer want to participate in the transparency scheme? (likely a bad sign)

**Comment by xAptive** [comment]
I believe between EXPIRES and PANICKEY, all the main use cases are covered.  The purpose of these messages is to show the current state of your system.  So if a publisher isn't happy with the current state, they should publish a new message.  If they no longer wish to participate, they should let it expire, or better yet, publish a new message with the current time (or past time), which will expire immediately.  And there is PANICKEY for everything else.

The one strange case that would be nice to cover, but may be impossible, is loss of signing keys, but not compromise of signing keys.  If with a multi-sig situation, there will certainly come a time when someone can't sign anymore.  As it stands now, those users will have to essentially just start using a new PUBKEY, and post some message explaining what happened.  Such a message is, of course, not necessarily to be trusted in some cases.  A case like this should trigger alerts for monitors, which is unfortunate as nothing has really gone wrong.

But I can't think of a great technical solution for this case that doesn't also impact security.  Only thing I can think of is having PANICKEY used in multiple ways.  Using it wouldn't necessarily indicate compromise.  Something like { "CODES" { "KEY_LOSS": 1}} could be included in the signing message to indicate loss of keys, and that the PUBKEY in the message signed by PANICKEY is the new authoritative key.  Just a thought.

**Comment by carrotcypher** [comment]
Based on recent changes to the protocol and updates in other issues, I consider this one resolved. Thanks!
